// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Role string

const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type VoteType string

const (
	VoteTypeUpvote   VoteType = "upvote"
	VoteTypeDownvote VoteType = "downvote"
)

func (e *VoteType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VoteType(s)
	case string:
		*e = VoteType(s)
	default:
		return fmt.Errorf("unsupported scan type for VoteType: %T", src)
	}
	return nil
}

type NullVoteType struct {
	VoteType VoteType `json:"vote_type"`
	Valid    bool     `json:"valid"` // Valid is true if VoteType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVoteType) Scan(value interface{}) error {
	if value == nil {
		ns.VoteType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VoteType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVoteType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VoteType), nil
}

type Product struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Details      string      `json:"details"`
	Price        int32       `json:"price"`
	Owner        uuid.UUID   `json:"owner"`
	CreatedAt    time.Time   `json:"created_at"`
	SearchVector interface{} `json:"search_vector"`
}

type Review struct {
	ID        uuid.UUID `json:"id"`
	Product   uuid.UUID `json:"product"`
	Comment   *string   `json:"comment"`
	Stars     int32     `json:"stars"`
	Author    uuid.UUID `json:"author"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	Role         Role      `json:"role"`
	Name         string    `json:"name"`
	Balance      int32     `json:"balance"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type Vote struct {
	ID        uuid.UUID `json:"id"`
	Review    uuid.UUID `json:"review"`
	Voter     uuid.UUID `json:"voter"`
	Type      VoteType  `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}
