// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Product struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Details   string    `json:"details"`
	Price     int32     `json:"price"`
	CreatedAt time.Time `json:"created_at"`
}
