// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package repository

import (
	"context"
)

const findAllOrders = `-- name: FindAllOrders :many
SELECT id, details, created_at FROM orders ORDER BY created_at
`

func (q *Queries) FindAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, findAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.ID, &i.Details, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (details)
VALUES (
  $1
) RETURNING id, details, created_at
`

type InsertOrderParams struct {
	Details string `json:"details"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertOrder, arg.Details)
	var i Order
	err := row.Scan(&i.ID, &i.Details, &i.CreatedAt)
	return i, err
}
