// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products WHERE id = $1 RETURNING id, name, details, price, created_at
`

type DeleteProductParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Details,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const findAllProducts = `-- name: FindAllProducts :many
SELECT id, name, details, price, created_at FROM products ORDER BY created_at DESC
`

func (q *Queries) FindAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, findAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Details,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, details, price, created_at FROM products WHERE id = $1 LIMIT 1
`

type GetProductByIDParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Details,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products
  (name, details, price)
VALUES ( $1, $2, $3 )
RETURNING id, name, details, price, created_at
`

type InsertProductParams struct {
	Name    string `json:"name"`
	Details string `json:"details"`
	Price   int32  `json:"price"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, insertProduct, arg.Name, arg.Details, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Details,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
