// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products WHERE id = $1 RETURNING id, name, details, price, owner, created_at, search_vector
`

type DeleteProductParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Details,
		&i.Price,
		&i.Owner,
		&i.CreatedAt,
		&i.SearchVector,
	)
	return i, err
}

const findProductsPaged = `-- name: FindProductsPaged :many
SELECT id, name, details, price, owner, created_at, search_vector FROM products ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type FindProductsPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) FindProductsPaged(ctx context.Context, arg FindProductsPagedParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, findProductsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Details,
			&i.Price,
			&i.Owner,
			&i.CreatedAt,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, details, price, owner, created_at, search_vector FROM products WHERE id = $1 LIMIT 1
`

type GetProductByIDParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Details,
		&i.Price,
		&i.Owner,
		&i.CreatedAt,
		&i.SearchVector,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products
  (name, details, price, owner)
VALUES ( $1, $2, $3, current_setting('app.user_id')::uuid)
RETURNING id, name, details, price, owner, created_at, search_vector
`

type InsertProductParams struct {
	Name    string `json:"name"`
	Details string `json:"details"`
	Price   int32  `json:"price"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, insertProduct, arg.Name, arg.Details, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Details,
		&i.Price,
		&i.Owner,
		&i.CreatedAt,
		&i.SearchVector,
	)
	return i, err
}

const isProductOwner = `-- name: IsProductOwner :one
SELECT current_setting('app.user_id')::uuid = (
  SELECT owner FROM products WHERE id = $1
)
`

type IsProductOwnerParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) IsProductOwner(ctx context.Context, arg IsProductOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProductOwner, arg.ID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const searchForProducts = `-- name: SearchForProducts :many
SELECT id, name, details, price, owner, created_at, search_vector, ts_rank(search_vector, to_tsquery($1)) as relevance
FROM products
WHERE search_vector @@ to_tsquery($1)
ORDER BY relevance DESC
`

type SearchForProductsParams struct {
	ToTsquery string `json:"to_tsquery"`
}

type SearchForProductsRow struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Details      string      `json:"details"`
	Price        int32       `json:"price"`
	Owner        uuid.UUID   `json:"owner"`
	CreatedAt    time.Time   `json:"created_at"`
	SearchVector interface{} `json:"search_vector"`
	Relevance    float32     `json:"relevance"`
}

func (q *Queries) SearchForProducts(ctx context.Context, arg SearchForProductsParams) ([]SearchForProductsRow, error) {
	rows, err := q.db.Query(ctx, searchForProducts, arg.ToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchForProductsRow{}
	for rows.Next() {
		var i SearchForProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Details,
			&i.Price,
			&i.Owner,
			&i.CreatedAt,
			&i.SearchVector,
			&i.Relevance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
  name = coalesce($1, name),
  details = coalesce($2, details),
  price = coalesce($3, price)
WHERE id = $4
RETURNING id, name, details, price, owner, created_at, search_vector
`

type UpdateProductParams struct {
	Name    *string   `json:"name"`
	Details *string   `json:"details"`
	Price   *int32    `json:"price"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Details,
		arg.Price,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Details,
		&i.Price,
		&i.Owner,
		&i.CreatedAt,
		&i.SearchVector,
	)
	return i, err
}
