// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reviews.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const deleteReview = `-- name: DeleteReview :one
DELETE FROM reviews WHERE id = $1 RETURNING id, product, comment, stars, author, created_at
`

type DeleteReviewParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) DeleteReview(ctx context.Context, arg DeleteReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, deleteReview, arg.ID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Comment,
		&i.Stars,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewsForProduct = `-- name: GetReviewsForProduct :many
SELECT id, product, comment, stars, author, created_at FROM reviews WHERE product = $1 ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetReviewsForProductParams struct {
	Product uuid.UUID `json:"product"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) GetReviewsForProduct(ctx context.Context, arg GetReviewsForProductParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, getReviewsForProduct, arg.Product, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.Product,
			&i.Comment,
			&i.Stars,
			&i.Author,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews
( product, comment, stars, author )
VALUES ( $1, $2, $3, current_setting('app.user_id')::uuid )
RETURNING id, product, comment, stars, author, created_at
`

type InsertReviewParams struct {
	Product uuid.UUID `json:"product"`
	Comment *string   `json:"comment"`
	Stars   int32     `json:"stars"`
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, insertReview, arg.Product, arg.Comment, arg.Stars)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.Product,
		&i.Comment,
		&i.Stars,
		&i.Author,
		&i.CreatedAt,
	)
	return i, err
}

const isOwnerOrAuthor = `-- name: IsOwnerOrAuthor :one
SELECT EXISTS (
  SELECT 1 FROM reviews r
  LEFT JOIN products p ON r.product = p.id
  WHERE r.id = $1 AND (
    current_setting('app.user_id')::UUID IN (
      r.author,
      p.owner
    )
  )
)
`

type IsOwnerOrAuthorParams struct {
	ID uuid.UUID `json:"id"`
}

func (q *Queries) IsOwnerOrAuthor(ctx context.Context, arg IsOwnerOrAuthorParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOwnerOrAuthor, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
