// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, email, username, role, name, balance, created_at
`

type DeleteUserParams struct {
	ID uuid.UUID `json:"id"`
}

type DeleteUserRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	Role      Role      `json:"role"`
	Name      string    `json:"name"`
	Balance   int32     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (DeleteUserRow, error) {
	row := q.db.QueryRow(ctx, deleteUser, arg.ID)
	var i DeleteUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
	email, username, name, password_hash
) VALUES ( $1, $2, $3, crypt($4, gen_salt('bf')) )
RETURNING id, email, username, name, balance
`

type InsertUserParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Name     string `json:"name"`
	Crypt    string `json:"crypt"`
}

type InsertUserRow struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Username string    `json:"username"`
	Name     string    `json:"name"`
	Balance  int32     `json:"balance"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.Username,
		arg.Name,
		arg.Crypt,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.Balance,
	)
	return i, err
}

const is = `-- name: Is :one
SELECT current_setting('app.user_id')::uuid = $1::uuid
`

type IsParams struct {
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) Is(ctx context.Context, arg IsParams) (bool, error) {
	row := q.db.QueryRow(ctx, is, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setConfig = `-- name: SetConfig :one
SELECT set_config('app.user_id', $1, false)
`

type SetConfigParams struct {
	UserID string `json:"user_id"`
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) (string, error) {
	row := q.db.QueryRow(ctx, setConfig, arg.UserID)
	var set_config string
	err := row.Scan(&set_config)
	return set_config, err
}

const unsafeGetUserByEmail = `-- name: UnsafeGetUserByEmail :one
SELECT id, email, username, role, name, balance, password_hash, created_at FROM users WHERE email = $1
`

type UnsafeGetUserByEmailParams struct {
	Email string `json:"email"`
}

func (q *Queries) UnsafeGetUserByEmail(ctx context.Context, arg UnsafeGetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, unsafeGetUserByEmail, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Role,
		&i.Name,
		&i.Balance,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users
SET
  email = coalesce($2, email),
  username = coalesce($3, username),
  name = coalesce($4, name)
WHERE id = $1
RETURNING id, email, username, name, balance
`

type UpdateUserInfoParams struct {
	ID       uuid.UUID `json:"id"`
	Email    *string   `json:"email"`
	Username *string   `json:"username"`
	Name     *string   `json:"name"`
}

type UpdateUserInfoRow struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	Username string    `json:"username"`
	Name     string    `json:"name"`
	Balance  int32     `json:"balance"`
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (UpdateUserInfoRow, error) {
	row := q.db.QueryRow(ctx, updateUserInfo,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Name,
	)
	var i UpdateUserInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Name,
		&i.Balance,
	)
	return i, err
}

const verifyAuth = `-- name: VerifyAuth :one
SELECT EXISTS (
  SELECT 1
  FROM users
  WHERE email = $1
  AND password_hash = crypt($2, password_hash)
) AS valid
`

type VerifyAuthParams struct {
	Email string `json:"email"`
	Crypt string `json:"crypt"`
}

func (q *Queries) VerifyAuth(ctx context.Context, arg VerifyAuthParams) (bool, error) {
	row := q.db.QueryRow(ctx, verifyAuth, arg.Email, arg.Crypt)
	var valid bool
	err := row.Scan(&valid)
	return valid, err
}
