// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: votes.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const insertVote = `-- name: InsertVote :one
INSERT INTO votes (review, voter, type)
VALUES ( $1, current_setting('app.user_id')::uuid, $2 )
RETURNING id, review, voter, type, created_at
`

type InsertVoteParams struct {
	Review uuid.UUID `json:"review"`
	Type   VoteType  `json:"type"`
}

func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) (Vote, error) {
	row := q.db.QueryRow(ctx, insertVote, arg.Review, arg.Type)
	var i Vote
	err := row.Scan(
		&i.ID,
		&i.Review,
		&i.Voter,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
